### Teste de Cadastro de Turista
POST http://127.0.0.1:5000/cadastrar
Content-Type: application/json

{
    "nome": "João Turista",
    "idade": 30,
    "telefone": "1199998888",
    "email": "joao@turista.com",
    "senha": "senha123",
    "tipo_usuario": "Turista"
}

### Teste de Cadastro de Parceiro
POST http://127.0.0.1:5000/cadastrar
Content-Type: application/json

{
    "nome": "Maria Parceira",
    "idade": 45,
    "telefone": "2177776666",
    "email": "maria@parceira.com",
    "senha": "senha456",
    "tipo_usuario": "Parceiro"
}

### Teste de Cadastro de Administrador
POST http://127.0.0.1:5000/cadastrar
Content-Type: application/json

{
    "nome": "Admin Supremo",
    "idade": 50,
    "telefone": "3155554444",
    "email": "admin@empresa.com",
    "senha": "adminseguro",
    "tipo_usuario": "Administrador"
}

### Teste de Login de Administrador (Sucesso)
POST http://127.0.0.1:5000/entrar
Content-Type: application/json

{
    "email": "admin@empresa.com",
    "senha": "adminseguro"
}

### Teste de Login de Parceiro (Sucesso)
POST http://127.0.0.1:5000/entrar
Content-Type: application/json

{
    "email": "maria@parceira.com",
    "senha": "senha456"
}

### Teste de Login de Turista (Sucesso)
POST http://127.0.0.1:5000/entrar
Content-Type: application/json

{
    "email": "joao@turista.com",
    "senha": "senha123"
}


### Teste de Edição de Publicação (Admin)
POST http://127.0.0.1:5000/publicacao/editar
Content-Type: application/json

{
    "admin_email": "admin@empresa.com",
    "titulo": "Novidade: Roteiro de Verão 2026",
    "descricao": "Prepare-se para as melhores viagens do ano!",
    "imagem": "link_para_nova_imagem_verao.jpg"
}

### Teste de Exclusão/Reset de Publicação (Admin)
POST http://127.0.0.1:5000/publicacao/excluir
Content-Type: application/json

{
    "admin_email": "admin@empresa.com"
}

### Teste de Cadastro de Passeio (Parceiro)
POST http://127.0.0.1:5000/passeio/cadastrar
Content-Type: application/json

{
    "parceiro_email": "maria@parceiro.com",
    "titulo": "Trilha para a Pedra da Gávea",
    "descricao": "Uma aventura desafiadora com vista panorâmica do Rio de Janeiro.",
    "valor": 75.00,
    "imagem_url": "link_imagem_pedra_gavea.jpg"
}

### Teste de Falha (Tentativa de Cadastro por Turista)
POST http://127.0.0.1:5000/passeio/cadastrar
Content-Type: application/json

{
    "parceiro_email": "joao@turista.com", 
    "titulo": "Praia de Copacabana",
    "descricao": "Passeio simples e relaxante.",
    "valor": 10.00,
    "imagem_url": "link_copacabana.jpg"
}

### Teste de Exibição de Passeios (Público)
GET http://127.0.0.1:5000/passeios